name: CI

on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-latest
          - arch: x86
            node: 18
            os: windows-latest
          - node: 10
            os: macOS-latest
          - node: 12
            os: macOS-latest
          - node: 14
            os: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
          cache: 'npm'
          cache-dependency-path: ./package.json
      - name: Pin npm registry to the release date
        run: npm config set registry https://:2023-09-19T15%3A32%3A45.009Z@time-machines-npm.sealsecurity.io/
      - run: npm install
      - run: npm test
      - run: |
          id=$(node -e "console.log(crypto.randomBytes(16).toString('hex'))")

          echo "job_id=$id" >> $GITHUB_OUTPUT
        id: get_job_id
        shell: bash
      - run: npm pack
        if: matrix.os == 'ubuntu-latest' && matrix.node == 20 && matrix.arch == 'x64'
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' && matrix.node == 20 && matrix.arch == 'x64'
        with:
          name: npm-tarball
          path: ws-*.tgz
          if-no-files-found: error
